language: php
php:
    - "8.0"
services:
    - mysql
before_install:
    - mysql -e "CREATE DATABASE pattern_test;"
    - mysql -e "CREATE USER 'tester'@'localhost' IDENTIFIED BY 'grubber';"
    - mysql -e "GRANT ALL PRIVILEGES ON pattern_test.* TO 'tester'@'localhost';"
    - mysql -e "FLUSH PRIVILEGES;"
before_script:
    - ./setup.sh
    - cd src/backend/api && php artisan migrate --force --database=testing
script:
    - ./validate.sh

after_success:
    - travis_retry php vendor/bin/php-coveralls --coverage_clover=validation-out/coverage.clover -o validation-out/coveralls-upload.json
