version: "3"
networks:
  pattern:
    ipam:
      driver: default

services:
  db:
    build: ./src/backend/sql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - TZ=Europe/Stockholm
