addons:
  sauce_connect:
    username: "oauth-miek1128-9ea9e"
    access_key: "1e810be1-a232-4cfc-b517-902a81982e69"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc